# Generated by Django 2.0.6 on 2018-06-07 23:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CallRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(choices=[('S', 'Start'), ('E', 'End')], max_length=1)),
                ('record_timestamp', models.DateTimeField()),
                ('call_id', models.CharField(max_length=255)),
                ('source_number', models.CharField(blank=True, max_length=11, validators=[django.core.validators.RegexValidator(message='Phone numbers must be all digits,         with 2 area code digits and 8 or 9 phone number digits.', regex='^\\d{10,11}')])),
                ('destination_number', models.CharField(blank=True, max_length=11, validators=[django.core.validators.RegexValidator(message='Phone numbers must be all digits,         with 2 area code digits and 8 or 9 phone number digits.', regex='^\\d{10,11}')])),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='callrecord',
            unique_together={('record_type', 'call_id')},
        ),
    ]
