# Generated by Django 2.0.6 on 2018-06-08 18:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callrecord',
            name='destination_number',
            field=models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator(code='invalid_phone_number', message='Phone numbers must be all digits, with 2 area code digits and 8 or 9 phone number digits.', regex='^\\d{10,11}$')]),
        ),
        migrations.AlterField(
            model_name='callrecord',
            name='source_number',
            field=models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator(code='invalid_phone_number', message='Phone numbers must be all digits, with 2 area code digits and 8 or 9 phone number digits.', regex='^\\d{10,11}$')]),
        ),
    ]
