# Generated by Django 2.0.6 on 2018-06-08 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0002_auto_20180608_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callrecord',
            name='call_id',
            field=models.PositiveIntegerField(),
        ),
    ]
