# Generated by Django 2.0.6 on 2018-06-10 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0004_auto_20180608_1744'),
    ]

    operations = [
        migrations.RenameField(
            model_name='callrecord',
            old_name='record_type',
            new_name='type',
        ),
        migrations.AlterUniqueTogether(
            name='callrecord',
            unique_together={('type', 'call_id')},
        ),
    ]
