# Generated by Django 2.0.6 on 2018-06-10 18:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0005_auto_20180609_2214'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallTariff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_tariff', models.DecimalField(decimal_places=2, max_digits=15)),
                ('minute_charge', models.DecimalField(decimal_places=2, max_digits=15)),
                ('discount_charge', models.DecimalField(decimal_places=2, max_digits=15)),
                ('valid_after', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='PhoneBill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(code='invalid_phone_number', message='Phone numbers must be all digits, with 2 area code digits and 8 or 9 phone number digits.', regex='^\\d{10,11}$')])),
                ('start_timestamp', models.DateTimeField()),
                ('call_duration', models.PositiveIntegerField()),
                ('charge', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
        ),
    ]
