# Generated by Django 2.0.6 on 2018-06-11 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0006_calltariff_phonebill'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='callrecord',
            unique_together={('type', 'call_id'), ('source', 'timestamp'), ('destination', 'timestamp')},
        ),
    ]
