# Generated by Django 2.0.6 on 2018-06-11 05:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0007_auto_20180611_0140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callrecord',
            name='destination',
            field=models.CharField(max_length=11, null=True, validators=[django.core.validators.RegexValidator(code='invalid_phone_number', message='Phone numbers must be all digits, with 2 area code digits and 8 or 9 phone number digits.', regex='^\\d{10,11}$')]),
        ),
        migrations.AlterField(
            model_name='callrecord',
            name='source',
            field=models.CharField(max_length=11, null=True, validators=[django.core.validators.RegexValidator(code='invalid_phone_number', message='Phone numbers must be all digits, with 2 area code digits and 8 or 9 phone number digits.', regex='^\\d{10,11}$')]),
        ),
        migrations.AlterUniqueTogether(
            name='callrecord',
            unique_together={('type', 'call_id')},
        ),
    ]
