# Generated by Django 2.0.6 on 2018-06-11 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0008_auto_20180611_0229'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='callrecord',
            unique_together={('call_id', 'timestamp'), ('type', 'call_id')},
        ),
    ]
