# Generated by Django 2.0.6 on 2018-06-11 20:06

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0010_auto_20180611_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonebill',
            name='charge',
            field=models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
